export const mockOwnerData = {
  futsal: {
    id: 1,
    name: "Champions Arena",
    status: "active",
    description:
      "Premium futsal facility with modern amenities and professional-grade artificial turf. Perfect for competitive matches and training sessions.",
    location: "Lalitpur, Nepal",
    coordinates: { lat: 27.6588, lng: 85.3247 },
    workingHours: "06:00 - 22:00",
    phone: "+977-9841234567",
    website: "www.championsarena.com.np",
    images: [
      "/api/placeholder/400/300",
      "/api/placeholder/400/300",
      "/api/placeholder/400/300",
    ],
    rating: 4.8,
    totalReviews: 156,
    amenities: ["Parking", "Changing Rooms", "Water", "First Aid", "Lighting"],
    pricing: {
      morning: 1500,
      afternoon: 2000,
      evening: 2500,
      night: 2000,
    },
  },
  stats: {
    todayBookings: 8,
    slotsRemaining: 4,
    totalCollected: 485600,
    thisMonthRevenue: 125400,
    totalBookings: 1247,
    averageRating: 4.8,
    occupancyRate: 78,
  },
  transactions: [
    {
      id: "abc123",
      amount: 2500,
      status: "paid",
      bookedBy: "Ram Sharma",
      date: "2025-06-04",
      time: "18:00-19:00",
      action: "completed",
    },
    {
      id: "xyz456",
      amount: 2000,
      status: "pending",
      bookedBy: "Sita Patel",
      date: "2025-06-04",
      time: "20:00-21:00",
      action: "pending",
    },
    {
      id: "def789",
      amount: 1500,
      status: "paid",
      bookedBy: "Hari Thapa",
      date: "2025-06-03",
      time: "07:00-08:00",
      action: "completed",
    },
    {
      id: "ghi012",
      amount: 2500,
      status: "cancelled",
      bookedBy: "Maya Gurung",
      date: "2025-06-03",
      time: "19:00-20:00",
      action: "refund",
    },
    {
      id: "jkl345",
      amount: 2000,
      status: "paid",
      bookedBy: "Rajesh KC",
      date: "2025-06-02",
      time: "16:00-17:00",
      action: "completed",
    },
  ],
  todayBookings: [
    {
      id: 1,
      time: "07:00-08:00",
      duration: 60,
      type: "Personal",
      bookedBy: "John Doe",
      price: 1500,
      status: "confirmed",
    },
    {
      id: 2,
      time: "09:00-10:00",
      duration: 60,
      type: "Team Practice",
      bookedBy: "ABC Sports Club",
      price: 1500,
      status: "confirmed",
    },
    {
      id: 3,
      time: "18:00-19:00",
      duration: 60,
      type: "Match",
      bookedBy: "Team Alpha vs Team Beta",
      price: 2500,
      status: "confirmed",
    },
    {
      id: 4,
      time: "20:00-21:00",
      duration: 60,
      type: "Training",
      bookedBy: "Youth Academy",
      price: 2000,
      status: "pending",
    },
  ],
  notifications: [
    {
      id: 1,
      message: "New booking request for tomorrow 6 PM",
      type: "booking",
      time: "2 mins ago",
      unread: true,
    },
    {
      id: 2,
      message: "Payment received for booking #abc123",
      type: "payment",
      time: "1 hour ago",
      unread: true,
    },
    {
      id: 3,
      message: "Booking cancelled for today 7 PM - refund processed",
      type: "cancellation",
      time: "3 hours ago",
      unread: false,
    },
  ],
  calendar: {
    currentMonth: "June 2025",
    dates: Array.from({ length: 30 }, (_, i) => ({
      date: i + 1,
      bookings: Math.floor(Math.random() * 12),
      revenue: Math.floor(Math.random() * 25000) + 5000,
    })),
  },
};
export function formatCurrency(amount: number) {
  return new Intl.NumberFormat("en-NP", {
    style: "currency",
    currency: "NPR",
    minimumFractionDigits: 0,
  }).format(amount);
}
